---
title: "COVID Tracker"
runtime: shiny
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    source_code: embed
    theme: yeti
    vertical_layout: fill
---

```{r global, include = FALSE}

library(tidyverse)
library(sf)

# Interactive Data Viz
library(leaflet)  # Maps
library(dygraphs) # Charts
library(rvest)    # webscraping
library(highcharter)
library(zoo)
library(scales)
library(formattable)

# Shiny
library(shiny)       # Starting Reactivity
library(flexdashboard)

source("helper.R")
counties = readRDS("counties.rds")
pop = readxl::read_excel('PopulationEstimates.xls', skip = 2) %>%
  select(state = State, pop_19 = POP_ESTIMATE_2019, fips = FIPStxt)
pop$fips <- as.numeric(pop$fips)
```





```{r context = "server"}
# # Initalize data
covid19 <- readRDS("covid_data.rds")
# covid19  <-  read_covid19()
today    <-  today_centroids(counties, covid19)
# basemap  <-  basemap(today)

today_2 <- today_centroids_2(counties, pop, covid19)
basemap <- basemap2(today, today_2)
# basemap_2 <- roll_mean_map(today_2)
```


```{r context = "server"}
FIP <- today$fips[which.max(today$cases)]
v   <- reactiveValues(msg = "")

output$covidMap     <- renderLeaflet({ basemap2(today, today_2) })
# county_lst <- USAboundaries::us_counties() %>% 
#   st_drop_geometry()
```

COVID-19 Tracker {data-icon="fa-briefcase-medical"}
====================================
Inputs {.sidebar data-width=150}
-------------------------------------

### 
```{r}
# state, county, usage and sector UI outputs
uiOutput("countySelect")

verbatimTextOutput("fipText")
```

###
```{r}
actionButton("submitButton", "Search", class = "btn-primary ")
```

Column {data-width=330}
-------------------------------------
### USA CASES
```{r}
valueBoxOutput("totalCases")
```

### USA DEATHS
```{r}
valueBoxOutput("totalDeaths")
```

### USA DEATH RATE
```{r}
valueBoxOutput("deathRate")
```

### 
```{r}
formattableOutput('covidTable')
```

```{r context = "server"}
countyInput <- observeEvent(input$submitButton, {
  if(is.null(input$countySearch)) {
    NULL
  } else {
      new_cases <- daily_county_cases(covid19, input$countySearch)
      new_deaths <- daily_county_deaths(covid19, input$countySearch)
      us_case <- total_us_cases(covid19)
      us_deaths <- total_us_deaths(covid19)
    
      output$covidGraph = renderDygraph({ make_graph(covid19, input$countySearch) })
      output$covidTable = renderFormattable({ make_table2(today, input$countySearch) })
      output$covidNewCases = renderHighchart({ 
          highchart() %>% 
              hc_xAxis(type = "datetime", dateTimeLabelFormats = list(month = "%b", year = "%y")) %>%
              hc_add_series(new_cases, name = "Daily cases", type = "column", hcaes(Date, new_cases)) %>%
              hc_add_series(new_cases, name = "7 day rolling mean", type = "line", hcaes(Date, rolling_mean)) %>%
              hc_plotOptions(column = list(pointWidth = 6,
                                           dataLabels = list(enabled = FALSE),
                                           enableMouseTracking = TRUE)) %>%
              hc_colors(c("lightblue", "darkcyan"))
      })
      output$covidNewDeaths <- renderHighchart({ 
          highchart() %>%
              hc_xAxis(type = "datetime", dateTimeLabelFormats = list(month = "%b", year = "%y")) %>%
              hc_add_series(new_deaths, name = "Daily deaths", type = "column", hcaes(Date, new_deaths)) %>%
              hc_add_series(new_deaths, name = "7 day Rolling mean", type = "line", hcaes(Date, rolling_mean)) %>%
              hc_plotOptions(column = list(pointWidth = 6,
                                           dataLabels = list(enabled = FALSE),
                                           enableMouseTracking = TRUE)) %>%
              hc_colors(c("pink", "darkred"))
      })
          leafletProxy("covidMap") %>%
              zoom_to_county(counties, input$countySearch)
  }
})

# County input
output$countySelect <- renderUI({
   selectInput("countySearch", "FIPS codes:",
               choices = as.list(sort(counties$fips)),
               multiple= FALSE,
               selectize = TRUE)
})
# Render total US cases
output$totalCases <- renderValueBox({
    valueBox(
      paste0((cases_info(covid19)[2])),
      icon = icon("user"),
      color = "orange") })

# Render total US deaths
output$totalDeaths <- renderValueBox({
    valueBox(
      paste0((cases_info(covid19)[1])),
      icon = icon("skull"),
      color = "danger") })

# Render US death rate
output$deathRate <- renderValueBox({
    valueBox(
      paste0((death_info(covid19)[5]), "%"),
      icon = icon("heart"),
  color = "grey")
      })
```


Column {data-width=900}
-------------------------------------

### {data-height=200}
```{r}
dygraphOutput("covidGraph")
```

### 
```{r}
leafletOutput("covidMap")
```

Column {.tabset}
--------------------------------------
### Daily cases
```{r}
  highchartOutput("covidNewCases")
```

### Daily deaths
```{r}
highchartOutput("covidNewDeaths")
```
 

```{r context = "server"}
# Observes if MAP 1 is clicked, zooms to clicked county, renders graphs, tables, value boxes
observeEvent(input$covidMap_marker_click, {
    FIP <<- input$covidMap_marker_click$id
    leafletProxy('covidMap') %>% zoom_to_county(counties, FIP)

  })
# Observes if MAP 2 is clicked, zooms to clicked county, renders graphs, tables, value boxes
observeEvent(input$covidMap2_marker_click, {
    FIP <<- input$covidMap2_marker_click$id
    leafletProxy('covidMap2') %>% zoom_to_county(counties, FIP)
  })
# autocomplete_input("auto", "Search for a County:",
#                                 value = "",
#                                 max_options = 5,
#                                 structure(today$fips, names = today$name))
# Observes search box, when county is searched, counties FIP code used to render graphs, tables, values boxes
# observe(
#     if(input$auto == ""){
#       NULL
#     } else {
#       FIP <<- input$auto
#       leafletProxy("covidMap") %>%
#         zoom_to_county(counties, FIP)
#       output$covidChart <- renderDygraph({ make_graph(covid19, FIP) })
#       output$covidTable <- renderFormattable({ make_table2(today, FIP) })
#       output$covidNewCases = renderPlotly({ daily_cases_graph(covid19, FIP) })
#       output$covidNewDeaths <- renderPlotly({ daily_deaths_graph(covid19, FIP) })
#       leafletProxy("covidMap2") %>%
#           zoom_to_county(counties, FIP)
#     }
#     )
```

```{r context = "server"}
# Observes if MAP 1 is clicked, zooms to clicked county, renders graphs, tables, value boxes
observeEvent(input$covidMap_marker_click, {
    FIP <<- input$covidMap_marker_click$id
    leafletProxy('covidMap') %>% zoom_to_county(counties, FIP)
    
    new_cases <- daily_county_cases(covid19, FIP)
    new_deaths <- daily_county_deaths(covid19, FIP)
    us_case <- total_us_cases(covid19)
    us_deaths <- total_us_deaths(covid19)
    
    output$covidGraph = renderDygraph({ make_graph(covid19, FIP) })
    output$covidTable = renderFormattable({ make_table2(today, FIP) })
    output$covidNewCases = renderHighchart({ 
      highchart() %>%
          hc_xAxis(type = "datetime", dateTimeLabelFormats = list(month = "%b", year = "%y")) %>%
          hc_add_series(new_cases, name = "Daily cases", type = "column", hcaes(Date, new_cases)) %>%
          hc_add_series(new_cases, name = "7 day rolling mean", type = "line", hcaes(Date, rolling_mean)) %>%
          hc_plotOptions(column = list(pointWidth = 6,
                                       dataLabels = list(enabled = FALSE),
                                       enableMouseTracking = TRUE)) %>%
          hc_colors(c("lightblue", "darkcyan"))
      })
    output$covidNewDeaths <- renderHighchart({ 
      highchart() %>%
          hc_xAxis(type = "datetime", dateTimeLabelFormats = list(month = "%b", year = "%y")) %>%
          hc_add_series(new_deaths, name = "Daily deaths", type = "column", hcaes(Date, new_deaths)) %>%
          hc_add_series(new_deaths, name = "7 day Rolling mean", type = "line", hcaes(Date, rolling_mean)) %>%
          hc_plotOptions(column = list(pointWidth = 6,
                                       dataLabels = list(enabled = FALSE),
                                       enableMouseTracking = TRUE)) %>%
          hc_colors(c("pink", "darkred"))
      })
  })
# Observes if MAP 2 is clicked, zooms to clicked county, renders graphs, tables, value boxes
observeEvent(input$covidMap2_marker_click, {
    FIP <<- input$covidMap2_marker_click$id
    leafletProxy('covidMap2') %>% zoom_to_county(counties, FIP)
    
    output$covidGraph = renderDygraph({ make_graph(covid19, FIP) })
    output$covidTable = renderFormattable({ make_table2(today, FIP) })
    output$covidNewCases = renderHighchart({ 
      highchart() %>%
          hc_xAxis(type = "datetime", dateTimeLabelFormats = list(month = "%b", year = "%y")) %>%
          hc_add_series(new_cases, type = "column", hcaes(Date, new_cases)) %>%
          hc_add_series(new_cases, type = "line", hcaes(Date, rolling_mean)) %>%
          hc_plotOptions(column = list(pointWidth = 6,
                                       dataLabels = list(enabled = FALSE),
                                       enableMouseTracking = TRUE)) %>%
          hc_colors(c("darkcyan", "darkred"))
      })
    output$covidNewDeaths <- renderHighchart({ 
      highchart() %>%
          hc_xAxis(type = "datetime", dateTimeLabelFormats = list(month = "%b", year = "%y")) %>%
          hc_add_series(new_deaths, name = "Daily deaths", type = "column", hcaes(Date, new_deaths)) %>%
          hc_add_series(new_deaths, name = "Rolling mean", type = "line", hcaes(Date, rolling_mean)) %>%
          hc_plotOptions(column = list(pointWidth = 6,
                                       dataLabels = list(enabled = FALSE),
                                       enableMouseTracking = TRUE)) %>%
          hc_colors(c("grey", "black"))
      })

  })
```













